apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-ui
  template:
    metadata:
      labels:
        app: todo-ui
    spec:
      containers:
      - name: todo-ui
        image: anacr.azurecr.io/microui:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      # imagePullSecrets:
      # - name: acr-secret
