apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-ui
  template:
    metadata:
      labels:
        app: todo-ui
    spec:
      containers:
      - name: todo-ui
        image: myacr09.azurecr.io/touimicro:1749ce4ab3ca6739df565fc4e259937eaaac9ac9
        imagePullPolicy: Always
        ports:
        - containerPort: 80

