name: Build and Push React App to ACR

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: todoui
      IMAGE_TAG: ${{ github.sha }}
      ACR_NAME: anzacr1
      ACR_LOGIN_SERVER: anzacr1.azurecr.io

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1️. Login to Azure using OIDC
      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURECLIENTID }}
          tenant-id: ${{ secrets.AZURETENANTID }}
          subscription-id: ${{ secrets.AZURESUBSCRIPTIONID }}

      # 2️. Login to ACR using Azure CLI
      - name: Log in to ACR
        run: az acr login --name $ACR_NAME

      # 3️. Build and Push Docker image
      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG .
        
      # 4. image scaned via trivy
      - name: Scan Docker Image (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: $IMAGE_NAME:$IMAGE_TAG
          severity: CRITICAL,HIGH
          format: 'table'

      # 5. image tag and push
      - name: Tag and Push Docker Image
        run: |
          docker tag $IMAGE_NAME:$IMAGE_TAG $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG
          docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG
          
      # 6. Clean up (optional but recommended)
      - name: Clean up
        run: docker system prune -af
